/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.DocumentAI.Model;
using Cloudmersive.APIClient.NETCore.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentQuestionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentQuestionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentQuestionsRequest
        //private DocumentQuestionsRequest instance;

        public DocumentQuestionsRequestTests()
        {
            // TODO uncomment below to create an instance of DocumentQuestionsRequest
            //instance = new DocumentQuestionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentQuestionsRequest
        /// </summary>
        [Fact]
        public void DocumentQuestionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentQuestionsRequest
            //Assert.IsType<DocumentQuestionsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InputFile'
        /// </summary>
        [Fact]
        public void InputFileTest()
        {
            // TODO unit test for the property 'InputFile'
        }

        /// <summary>
        /// Test the property 'QuestionsYesNo'
        /// </summary>
        [Fact]
        public void QuestionsYesNoTest()
        {
            // TODO unit test for the property 'QuestionsYesNo'
        }

        /// <summary>
        /// Test the property 'QuestionsMultipleChoice'
        /// </summary>
        [Fact]
        public void QuestionsMultipleChoiceTest()
        {
            // TODO unit test for the property 'QuestionsMultipleChoice'
        }

        /// <summary>
        /// Test the property 'QuestionsFreeResponse'
        /// </summary>
        [Fact]
        public void QuestionsFreeResponseTest()
        {
            // TODO unit test for the property 'QuestionsFreeResponse'
        }

        /// <summary>
        /// Test the property 'RecognitionMode'
        /// </summary>
        [Fact]
        public void RecognitionModeTest()
        {
            // TODO unit test for the property 'RecognitionMode'
        }
    }
}
