/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.DocumentAI.Model;
using Cloudmersive.APIClient.NETCore.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentQuestionChoiceItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentQuestionChoiceItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentQuestionChoiceItem
        //private DocumentQuestionChoiceItem instance;

        public DocumentQuestionChoiceItemTests()
        {
            // TODO uncomment below to create an instance of DocumentQuestionChoiceItem
            //instance = new DocumentQuestionChoiceItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentQuestionChoiceItem
        /// </summary>
        [Fact]
        public void DocumentQuestionChoiceItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentQuestionChoiceItem
            //Assert.IsType<DocumentQuestionChoiceItem>(instance);
        }

        /// <summary>
        /// Test the property 'ChoiceId'
        /// </summary>
        [Fact]
        public void ChoiceIdTest()
        {
            // TODO unit test for the property 'ChoiceId'
        }

        /// <summary>
        /// Test the property 'ChoiceText'
        /// </summary>
        [Fact]
        public void ChoiceTextTest()
        {
            // TODO unit test for the property 'ChoiceText'
        }
    }
}
