/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.DocumentAI.Client;
using Cloudmersive.APIClient.NETCore.DocumentAI.Model;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAnalyzeApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Enforce Policies to a Document to allow or block it using Advanced AI
        /// </summary>
        /// <remarks>
        /// Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document and policy rules (optional)</param>
        /// <returns>DocumentPolicyResult</returns>
        DocumentPolicyResult ApplyRules (DocumentPolicyRequest body = null);

        /// <summary>
        /// Enforce Policies to a Document to allow or block it using Advanced AI
        /// </summary>
        /// <remarks>
        /// Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document and policy rules (optional)</param>
        /// <returns>ApiResponse of DocumentPolicyResult</returns>
        ApiResponse<DocumentPolicyResult> ApplyRulesWithHttpInfo (DocumentPolicyRequest body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Enforce Policies to a Document to allow or block it using Advanced AI
        /// </summary>
        /// <remarks>
        /// Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document and policy rules (optional)</param>
        /// <returns>Task of DocumentPolicyResult</returns>
        System.Threading.Tasks.Task<DocumentPolicyResult> ApplyRulesAsync (DocumentPolicyRequest body = null);

        /// <summary>
        /// Enforce Policies to a Document to allow or block it using Advanced AI
        /// </summary>
        /// <remarks>
        /// Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document and policy rules (optional)</param>
        /// <returns>Task of ApiResponse (DocumentPolicyResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DocumentPolicyResult>> ApplyRulesAsyncWithHttpInfo (DocumentPolicyRequest body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AnalyzeApi : IAnalyzeApi
    {
        private Cloudmersive.APIClient.NETCore.DocumentAI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyzeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AnalyzeApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyzeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AnalyzeApi(Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Enforce Policies to a Document to allow or block it using Advanced AI Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document and policy rules (optional)</param>
        /// <returns>DocumentPolicyResult</returns>
        public DocumentPolicyResult ApplyRules (DocumentPolicyRequest body = null)
        {
             ApiResponse<DocumentPolicyResult> localVarResponse = ApplyRulesWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Enforce Policies to a Document to allow or block it using Advanced AI Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document and policy rules (optional)</param>
        /// <returns>ApiResponse of DocumentPolicyResult</returns>
        public ApiResponse< DocumentPolicyResult > ApplyRulesWithHttpInfo (DocumentPolicyRequest body = null)
        {

            var localVarPath = "./document-ai/document/analyze/enforce-policy";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApplyRules", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DocumentPolicyResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DocumentPolicyResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DocumentPolicyResult)));
        }

        /// <summary>
        /// Enforce Policies to a Document to allow or block it using Advanced AI Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document and policy rules (optional)</param>
        /// <returns>Task of DocumentPolicyResult</returns>
        public async System.Threading.Tasks.Task<DocumentPolicyResult> ApplyRulesAsync (DocumentPolicyRequest body = null)
        {
             ApiResponse<DocumentPolicyResult> localVarResponse = await ApplyRulesAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Enforce Policies to a Document to allow or block it using Advanced AI Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document and policy rules (optional)</param>
        /// <returns>Task of ApiResponse (DocumentPolicyResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DocumentPolicyResult>> ApplyRulesAsyncWithHttpInfo (DocumentPolicyRequest body = null)
        {

            var localVarPath = "./document-ai/document/analyze/enforce-policy";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApplyRules", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DocumentPolicyResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DocumentPolicyResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DocumentPolicyResult)));
        }

    }
}
