/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.DocumentAI.Client;
using Cloudmersive.APIClient.NETCore.DocumentAI.Model;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IExtractApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Extract Classification or Category from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>DocumentClassificationResult</returns>
        DocumentClassificationResult ExtractClassification (string categories = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Extract Classification or Category from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of DocumentClassificationResult</returns>
        ApiResponse<DocumentClassificationResult> ExtractClassificationWithHttpInfo (string categories = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Extract Field Values from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fieldNames">Desired fields to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractFieldsResponse</returns>
        ExtractFieldsResponse ExtractFields (string fieldNames = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Extract Field Values from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fieldNames">Desired fields to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractFieldsResponse</returns>
        ApiResponse<ExtractFieldsResponse> ExtractFieldsWithHttpInfo (string fieldNames = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Extract Field Values from a Document using Advanced AI
        /// </summary>
        /// <remarks>
        /// Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document file as byte array, and information on which fields to extract (optional)</param>
        /// <returns>ExtractFieldsResponse</returns>
        ExtractFieldsResponse ExtractFieldsAdvanced (AdvancedExtractFieldsRequest body = null);

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI
        /// </summary>
        /// <remarks>
        /// Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document file as byte array, and information on which fields to extract (optional)</param>
        /// <returns>ApiResponse of ExtractFieldsResponse</returns>
        ApiResponse<ExtractFieldsResponse> ExtractFieldsAdvancedWithHttpInfo (AdvancedExtractFieldsRequest body = null);
        /// <summary>
        /// Extract Summary from a Document using AI
        /// </summary>
        /// <remarks>
        /// Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>SummarizeDocumentResponse</returns>
        SummarizeDocumentResponse ExtractSummary (System.IO.Stream inputFile = null);

        /// <summary>
        /// Extract Summary from a Document using AI
        /// </summary>
        /// <remarks>
        /// Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of SummarizeDocumentResponse</returns>
        ApiResponse<SummarizeDocumentResponse> ExtractSummaryWithHttpInfo (System.IO.Stream inputFile = null);
        /// <summary>
        /// Extract Tables of Data from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractFieldsResponse</returns>
        ExtractFieldsResponse ExtractTables (System.IO.Stream inputFile = null);

        /// <summary>
        /// Extract Tables of Data from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractFieldsResponse</returns>
        ApiResponse<ExtractFieldsResponse> ExtractTablesWithHttpInfo (System.IO.Stream inputFile = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Extract Classification or Category from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of DocumentClassificationResult</returns>
        System.Threading.Tasks.Task<DocumentClassificationResult> ExtractClassificationAsync (string categories = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Extract Classification or Category from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (DocumentClassificationResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DocumentClassificationResult>> ExtractClassificationAsyncWithHttpInfo (string categories = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Extract Field Values from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fieldNames">Desired fields to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ExtractFieldsResponse</returns>
        System.Threading.Tasks.Task<ExtractFieldsResponse> ExtractFieldsAsync (string fieldNames = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Extract Field Values from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fieldNames">Desired fields to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (ExtractFieldsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtractFieldsResponse>> ExtractFieldsAsyncWithHttpInfo (string fieldNames = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Extract Field Values from a Document using Advanced AI
        /// </summary>
        /// <remarks>
        /// Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document file as byte array, and information on which fields to extract (optional)</param>
        /// <returns>Task of ExtractFieldsResponse</returns>
        System.Threading.Tasks.Task<ExtractFieldsResponse> ExtractFieldsAdvancedAsync (AdvancedExtractFieldsRequest body = null);

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI
        /// </summary>
        /// <remarks>
        /// Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document file as byte array, and information on which fields to extract (optional)</param>
        /// <returns>Task of ApiResponse (ExtractFieldsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtractFieldsResponse>> ExtractFieldsAdvancedAsyncWithHttpInfo (AdvancedExtractFieldsRequest body = null);
        /// <summary>
        /// Extract Summary from a Document using AI
        /// </summary>
        /// <remarks>
        /// Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of SummarizeDocumentResponse</returns>
        System.Threading.Tasks.Task<SummarizeDocumentResponse> ExtractSummaryAsync (System.IO.Stream inputFile = null);

        /// <summary>
        /// Extract Summary from a Document using AI
        /// </summary>
        /// <remarks>
        /// Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (SummarizeDocumentResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SummarizeDocumentResponse>> ExtractSummaryAsyncWithHttpInfo (System.IO.Stream inputFile = null);
        /// <summary>
        /// Extract Tables of Data from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ExtractFieldsResponse</returns>
        System.Threading.Tasks.Task<ExtractFieldsResponse> ExtractTablesAsync (System.IO.Stream inputFile = null);

        /// <summary>
        /// Extract Tables of Data from a Document using AI
        /// </summary>
        /// <remarks>
        /// Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (ExtractFieldsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtractFieldsResponse>> ExtractTablesAsyncWithHttpInfo (System.IO.Stream inputFile = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ExtractApi : IExtractApi
    {
        private Cloudmersive.APIClient.NETCore.DocumentAI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ExtractApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ExtractApi(Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Extract Classification or Category from a Document using AI Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>DocumentClassificationResult</returns>
        public DocumentClassificationResult ExtractClassification (string categories = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<DocumentClassificationResult> localVarResponse = ExtractClassificationWithHttpInfo(categories, inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Classification or Category from a Document using AI Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of DocumentClassificationResult</returns>
        public ApiResponse< DocumentClassificationResult > ExtractClassificationWithHttpInfo (string categories = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./document-ai/document/extract/classify";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (categories != null) localVarHeaderParams.Add("Categories", this.Configuration.ApiClient.ParameterToString(categories)); // header parameter
            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractClassification", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DocumentClassificationResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DocumentClassificationResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DocumentClassificationResult)));
        }

        /// <summary>
        /// Extract Classification or Category from a Document using AI Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of DocumentClassificationResult</returns>
        public async System.Threading.Tasks.Task<DocumentClassificationResult> ExtractClassificationAsync (string categories = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<DocumentClassificationResult> localVarResponse = await ExtractClassificationAsyncWithHttpInfo(categories, inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Extract Classification or Category from a Document using AI Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (DocumentClassificationResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DocumentClassificationResult>> ExtractClassificationAsyncWithHttpInfo (string categories = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./document-ai/document/extract/classify";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (categories != null) localVarHeaderParams.Add("Categories", this.Configuration.ApiClient.ParameterToString(categories)); // header parameter
            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractClassification", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DocumentClassificationResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DocumentClassificationResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DocumentClassificationResult)));
        }

        /// <summary>
        /// Extract Field Values from a Document using AI Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fieldNames">Desired fields to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractFieldsResponse</returns>
        public ExtractFieldsResponse ExtractFields (string fieldNames = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<ExtractFieldsResponse> localVarResponse = ExtractFieldsWithHttpInfo(fieldNames, inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Field Values from a Document using AI Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fieldNames">Desired fields to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractFieldsResponse</returns>
        public ApiResponse< ExtractFieldsResponse > ExtractFieldsWithHttpInfo (string fieldNames = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./document-ai/document/extract/fields";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fieldNames != null) localVarHeaderParams.Add("FieldNames", this.Configuration.ApiClient.ParameterToString(fieldNames)); // header parameter
            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractFields", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtractFieldsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (ExtractFieldsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtractFieldsResponse)));
        }

        /// <summary>
        /// Extract Field Values from a Document using AI Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fieldNames">Desired fields to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ExtractFieldsResponse</returns>
        public async System.Threading.Tasks.Task<ExtractFieldsResponse> ExtractFieldsAsync (string fieldNames = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<ExtractFieldsResponse> localVarResponse = await ExtractFieldsAsyncWithHttpInfo(fieldNames, inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Extract Field Values from a Document using AI Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fieldNames">Desired fields to extract (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (ExtractFieldsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ExtractFieldsResponse>> ExtractFieldsAsyncWithHttpInfo (string fieldNames = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./document-ai/document/extract/fields";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fieldNames != null) localVarHeaderParams.Add("FieldNames", this.Configuration.ApiClient.ParameterToString(fieldNames)); // header parameter
            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractFields", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtractFieldsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (ExtractFieldsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtractFieldsResponse)));
        }

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document file as byte array, and information on which fields to extract (optional)</param>
        /// <returns>ExtractFieldsResponse</returns>
        public ExtractFieldsResponse ExtractFieldsAdvanced (AdvancedExtractFieldsRequest body = null)
        {
             ApiResponse<ExtractFieldsResponse> localVarResponse = ExtractFieldsAdvancedWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document file as byte array, and information on which fields to extract (optional)</param>
        /// <returns>ApiResponse of ExtractFieldsResponse</returns>
        public ApiResponse< ExtractFieldsResponse > ExtractFieldsAdvancedWithHttpInfo (AdvancedExtractFieldsRequest body = null)
        {

            var localVarPath = "./document-ai/document/extract/fields/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractFieldsAdvanced", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtractFieldsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (ExtractFieldsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtractFieldsResponse)));
        }

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document file as byte array, and information on which fields to extract (optional)</param>
        /// <returns>Task of ExtractFieldsResponse</returns>
        public async System.Threading.Tasks.Task<ExtractFieldsResponse> ExtractFieldsAdvancedAsync (AdvancedExtractFieldsRequest body = null)
        {
             ApiResponse<ExtractFieldsResponse> localVarResponse = await ExtractFieldsAdvancedAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request, including document file as byte array, and information on which fields to extract (optional)</param>
        /// <returns>Task of ApiResponse (ExtractFieldsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ExtractFieldsResponse>> ExtractFieldsAdvancedAsyncWithHttpInfo (AdvancedExtractFieldsRequest body = null)
        {

            var localVarPath = "./document-ai/document/extract/fields/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractFieldsAdvanced", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtractFieldsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (ExtractFieldsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtractFieldsResponse)));
        }

        /// <summary>
        /// Extract Summary from a Document using AI Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>SummarizeDocumentResponse</returns>
        public SummarizeDocumentResponse ExtractSummary (System.IO.Stream inputFile = null)
        {
             ApiResponse<SummarizeDocumentResponse> localVarResponse = ExtractSummaryWithHttpInfo(inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Summary from a Document using AI Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of SummarizeDocumentResponse</returns>
        public ApiResponse< SummarizeDocumentResponse > ExtractSummaryWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./document-ai/document/extract/summary";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractSummary", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SummarizeDocumentResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SummarizeDocumentResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SummarizeDocumentResponse)));
        }

        /// <summary>
        /// Extract Summary from a Document using AI Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of SummarizeDocumentResponse</returns>
        public async System.Threading.Tasks.Task<SummarizeDocumentResponse> ExtractSummaryAsync (System.IO.Stream inputFile = null)
        {
             ApiResponse<SummarizeDocumentResponse> localVarResponse = await ExtractSummaryAsyncWithHttpInfo(inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Extract Summary from a Document using AI Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (SummarizeDocumentResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SummarizeDocumentResponse>> ExtractSummaryAsyncWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./document-ai/document/extract/summary";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractSummary", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SummarizeDocumentResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SummarizeDocumentResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SummarizeDocumentResponse)));
        }

        /// <summary>
        /// Extract Tables of Data from a Document using AI Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractFieldsResponse</returns>
        public ExtractFieldsResponse ExtractTables (System.IO.Stream inputFile = null)
        {
             ApiResponse<ExtractFieldsResponse> localVarResponse = ExtractTablesWithHttpInfo(inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Tables of Data from a Document using AI Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractFieldsResponse</returns>
        public ApiResponse< ExtractFieldsResponse > ExtractTablesWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./document-ai/document/extract/tables";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractTables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtractFieldsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (ExtractFieldsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtractFieldsResponse)));
        }

        /// <summary>
        /// Extract Tables of Data from a Document using AI Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ExtractFieldsResponse</returns>
        public async System.Threading.Tasks.Task<ExtractFieldsResponse> ExtractTablesAsync (System.IO.Stream inputFile = null)
        {
             ApiResponse<ExtractFieldsResponse> localVarResponse = await ExtractTablesAsyncWithHttpInfo(inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Extract Tables of Data from a Document using AI Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (ExtractFieldsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ExtractFieldsResponse>> ExtractTablesAsyncWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./document-ai/document/extract/tables";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExtractTables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtractFieldsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (ExtractFieldsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtractFieldsResponse)));
        }

    }
}
