/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Cloudmersive.APIClient.NETCore.DocumentAI.Client;
using Cloudmersive.APIClient.NETCore.DocumentAI.Model;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRunBatchJobApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Extract All Fields and Tables of Data from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractDocumentBatchJobResult</returns>
        ExtractDocumentBatchJobResult ExtractAllFieldsAndTablesFromDocumentBatchJob(string? recognitionMode = default, FileParameter? inputFile = default);

        /// <summary>
        /// Extract All Fields and Tables of Data from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentBatchJobResult</returns>
        ApiResponse<ExtractDocumentBatchJobResult> ExtractAllFieldsAndTablesFromDocumentBatchJobWithHttpInfo(string? recognitionMode = default, FileParameter? inputFile = default);
        /// <summary>
        /// Extract Classification or Category from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractDocumentBatchJobResult</returns>
        ExtractDocumentBatchJobResult ExtractClassificationFromDocumentBatchJob(string? categories = default, string? recognitionMode = default, FileParameter? inputFile = default);

        /// <summary>
        /// Extract Classification or Category from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentBatchJobResult</returns>
        ApiResponse<ExtractDocumentBatchJobResult> ExtractClassificationFromDocumentBatchJobWithHttpInfo(string? categories = default, string? recognitionMode = default, FileParameter? inputFile = default);
        /// <summary>
        /// Extract Field Values from a Document using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="body">Input document and parameters (optional)</param>
        /// <returns>ExtractDocumentBatchJobResult</returns>
        ExtractDocumentBatchJobResult ExtractFieldsFromDocumentAdvancedBatchJob(string? recognitionMode = default, AdvancedExtractFieldsRequest? body = default);

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="body">Input document and parameters (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentBatchJobResult</returns>
        ApiResponse<ExtractDocumentBatchJobResult> ExtractFieldsFromDocumentAdvancedBatchJobWithHttpInfo(string? recognitionMode = default, AdvancedExtractFieldsRequest? body = default);
        /// <summary>
        /// Extract Text from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractDocumentBatchJobResult</returns>
        ExtractDocumentBatchJobResult ExtractTextFromDocumentBatchJob(string? recognitionMode = default, FileParameter? inputFile = default);

        /// <summary>
        /// Extract Text from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentBatchJobResult</returns>
        ApiResponse<ExtractDocumentBatchJobResult> ExtractTextFromDocumentBatchJobWithHttpInfo(string? recognitionMode = default, FileParameter? inputFile = default);
        /// <summary>
        /// Get the status and result of an Extract Document Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>ExtractDocumentJobStatusResult</returns>
        ExtractDocumentJobStatusResult GetAsyncJobStatus(string? asyncJobID = default);

        /// <summary>
        /// Get the status and result of an Extract Document Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentJobStatusResult</returns>
        ApiResponse<ExtractDocumentJobStatusResult> GetAsyncJobStatusWithHttpInfo(string? asyncJobID = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRunBatchJobApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Extract All Fields and Tables of Data from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentBatchJobResult</returns>
        System.Threading.Tasks.Task<ExtractDocumentBatchJobResult> ExtractAllFieldsAndTablesFromDocumentBatchJobAsync(string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Extract All Fields and Tables of Data from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtractDocumentBatchJobResult>> ExtractAllFieldsAndTablesFromDocumentBatchJobWithHttpInfoAsync(string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Extract Classification or Category from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentBatchJobResult</returns>
        System.Threading.Tasks.Task<ExtractDocumentBatchJobResult> ExtractClassificationFromDocumentBatchJobAsync(string? categories = default, string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Extract Classification or Category from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtractDocumentBatchJobResult>> ExtractClassificationFromDocumentBatchJobWithHttpInfoAsync(string? categories = default, string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Extract Field Values from a Document using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="body">Input document and parameters (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentBatchJobResult</returns>
        System.Threading.Tasks.Task<ExtractDocumentBatchJobResult> ExtractFieldsFromDocumentAdvancedBatchJobAsync(string? recognitionMode = default, AdvancedExtractFieldsRequest? body = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="body">Input document and parameters (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtractDocumentBatchJobResult>> ExtractFieldsFromDocumentAdvancedBatchJobWithHttpInfoAsync(string? recognitionMode = default, AdvancedExtractFieldsRequest? body = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Extract Text from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentBatchJobResult</returns>
        System.Threading.Tasks.Task<ExtractDocumentBatchJobResult> ExtractTextFromDocumentBatchJobAsync(string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Extract Text from a Document using AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtractDocumentBatchJobResult>> ExtractTextFromDocumentBatchJobWithHttpInfoAsync(string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get the status and result of an Extract Document Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentJobStatusResult</returns>
        System.Threading.Tasks.Task<ExtractDocumentJobStatusResult> GetAsyncJobStatusAsync(string? asyncJobID = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get the status and result of an Extract Document Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentJobStatusResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtractDocumentJobStatusResult>> GetAsyncJobStatusWithHttpInfoAsync(string? asyncJobID = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRunBatchJobApi : IRunBatchJobApiSync, IRunBatchJobApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RunBatchJobApi : IDisposable, IRunBatchJobApi
    {
        private Cloudmersive.APIClient.NETCore.DocumentAI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RunBatchJobApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public RunBatchJobApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunBatchJobApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public RunBatchJobApi(string basePath)
        {
            this.Configuration = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NETCore.DocumentAI.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunBatchJobApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public RunBatchJobApi(Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NETCore.DocumentAI.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunBatchJobApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RunBatchJobApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunBatchJobApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RunBatchJobApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NETCore.DocumentAI.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunBatchJobApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RunBatchJobApi(HttpClient client, Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NETCore.DocumentAI.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunBatchJobApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public RunBatchJobApi(Cloudmersive.APIClient.NETCore.DocumentAI.Client.ISynchronousClient client, Cloudmersive.APIClient.NETCore.DocumentAI.Client.IAsynchronousClient asyncClient, Cloudmersive.APIClient.NETCore.DocumentAI.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Extract All Fields and Tables of Data from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractDocumentBatchJobResult</returns>
        public ExtractDocumentBatchJobResult ExtractAllFieldsAndTablesFromDocumentBatchJob(string? recognitionMode = default, FileParameter? inputFile = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> localVarResponse = ExtractAllFieldsAndTablesFromDocumentBatchJobWithHttpInfo(recognitionMode, inputFile);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract All Fields and Tables of Data from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentBatchJobResult</returns>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> ExtractAllFieldsAndTablesFromDocumentBatchJobWithHttpInfo(string? recognitionMode = default, FileParameter? inputFile = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (recognitionMode != null)
            {
                localVarRequestOptions.HeaderParameters.Add("recognitionMode", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(recognitionMode)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("InputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ExtractDocumentBatchJobResult>("/document-ai/document/batch-job/extract/all", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractAllFieldsAndTablesFromDocumentBatchJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Extract All Fields and Tables of Data from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentBatchJobResult</returns>
        public async System.Threading.Tasks.Task<ExtractDocumentBatchJobResult> ExtractAllFieldsAndTablesFromDocumentBatchJobAsync(string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> localVarResponse = await ExtractAllFieldsAndTablesFromDocumentBatchJobWithHttpInfoAsync(recognitionMode, inputFile, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract All Fields and Tables of Data from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult>> ExtractAllFieldsAndTablesFromDocumentBatchJobWithHttpInfoAsync(string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (recognitionMode != null)
            {
                localVarRequestOptions.HeaderParameters.Add("recognitionMode", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(recognitionMode)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("InputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ExtractDocumentBatchJobResult>("/document-ai/document/batch-job/extract/all", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractAllFieldsAndTablesFromDocumentBatchJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Extract Classification or Category from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractDocumentBatchJobResult</returns>
        public ExtractDocumentBatchJobResult ExtractClassificationFromDocumentBatchJob(string? categories = default, string? recognitionMode = default, FileParameter? inputFile = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> localVarResponse = ExtractClassificationFromDocumentBatchJobWithHttpInfo(categories, recognitionMode, inputFile);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Classification or Category from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentBatchJobResult</returns>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> ExtractClassificationFromDocumentBatchJobWithHttpInfo(string? categories = default, string? recognitionMode = default, FileParameter? inputFile = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (categories != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Categories", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(categories)); // header parameter
            }
            if (recognitionMode != null)
            {
                localVarRequestOptions.HeaderParameters.Add("recognitionMode", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(recognitionMode)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("InputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ExtractDocumentBatchJobResult>("/document-ai/document/batch-job/extract/classify", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractClassificationFromDocumentBatchJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Extract Classification or Category from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentBatchJobResult</returns>
        public async System.Threading.Tasks.Task<ExtractDocumentBatchJobResult> ExtractClassificationFromDocumentBatchJobAsync(string? categories = default, string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> localVarResponse = await ExtractClassificationFromDocumentBatchJobWithHttpInfoAsync(categories, recognitionMode, inputFile, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Classification or Category from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="categories">Desired classification to extract (optional)</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult>> ExtractClassificationFromDocumentBatchJobWithHttpInfoAsync(string? categories = default, string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (categories != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Categories", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(categories)); // header parameter
            }
            if (recognitionMode != null)
            {
                localVarRequestOptions.HeaderParameters.Add("recognitionMode", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(recognitionMode)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("InputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ExtractDocumentBatchJobResult>("/document-ai/document/batch-job/extract/classify", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractClassificationFromDocumentBatchJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="body">Input document and parameters (optional)</param>
        /// <returns>ExtractDocumentBatchJobResult</returns>
        public ExtractDocumentBatchJobResult ExtractFieldsFromDocumentAdvancedBatchJob(string? recognitionMode = default, AdvancedExtractFieldsRequest? body = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> localVarResponse = ExtractFieldsFromDocumentAdvancedBatchJobWithHttpInfo(recognitionMode, body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="body">Input document and parameters (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentBatchJobResult</returns>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> ExtractFieldsFromDocumentAdvancedBatchJobWithHttpInfo(string? recognitionMode = default, AdvancedExtractFieldsRequest? body = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (recognitionMode != null)
            {
                localVarRequestOptions.HeaderParameters.Add("recognitionMode", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(recognitionMode)); // header parameter
            }
            localVarRequestOptions.Data = body;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ExtractDocumentBatchJobResult>("/document-ai/document/batch-job/extract/fields/advanced", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractFieldsFromDocumentAdvancedBatchJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="body">Input document and parameters (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentBatchJobResult</returns>
        public async System.Threading.Tasks.Task<ExtractDocumentBatchJobResult> ExtractFieldsFromDocumentAdvancedBatchJobAsync(string? recognitionMode = default, AdvancedExtractFieldsRequest? body = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> localVarResponse = await ExtractFieldsFromDocumentAdvancedBatchJobWithHttpInfoAsync(recognitionMode, body, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Field Values from a Document using Advanced AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="body">Input document and parameters (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult>> ExtractFieldsFromDocumentAdvancedBatchJobWithHttpInfoAsync(string? recognitionMode = default, AdvancedExtractFieldsRequest? body = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (recognitionMode != null)
            {
                localVarRequestOptions.HeaderParameters.Add("recognitionMode", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(recognitionMode)); // header parameter
            }
            localVarRequestOptions.Data = body;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ExtractDocumentBatchJobResult>("/document-ai/document/batch-job/extract/fields/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractFieldsFromDocumentAdvancedBatchJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Extract Text from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ExtractDocumentBatchJobResult</returns>
        public ExtractDocumentBatchJobResult ExtractTextFromDocumentBatchJob(string? recognitionMode = default, FileParameter? inputFile = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> localVarResponse = ExtractTextFromDocumentBatchJobWithHttpInfo(recognitionMode, inputFile);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Text from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentBatchJobResult</returns>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> ExtractTextFromDocumentBatchJobWithHttpInfo(string? recognitionMode = default, FileParameter? inputFile = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (recognitionMode != null)
            {
                localVarRequestOptions.HeaderParameters.Add("recognitionMode", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(recognitionMode)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("InputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ExtractDocumentBatchJobResult>("/document-ai/document/batch-job/extract/text", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractTextFromDocumentBatchJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Extract Text from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentBatchJobResult</returns>
        public async System.Threading.Tasks.Task<ExtractDocumentBatchJobResult> ExtractTextFromDocumentBatchJobAsync(string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult> localVarResponse = await ExtractTextFromDocumentBatchJobWithHttpInfoAsync(recognitionMode, inputFile, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract Text from a Document using AI as a Batch Job Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recognitionMode">Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentBatchJobResult>> ExtractTextFromDocumentBatchJobWithHttpInfoAsync(string? recognitionMode = default, FileParameter? inputFile = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (recognitionMode != null)
            {
                localVarRequestOptions.HeaderParameters.Add("recognitionMode", Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToString(recognitionMode)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("InputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ExtractDocumentBatchJobResult>("/document-ai/document/batch-job/extract/text", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractTextFromDocumentBatchJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the status and result of an Extract Document Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>ExtractDocumentJobStatusResult</returns>
        public ExtractDocumentJobStatusResult GetAsyncJobStatus(string? asyncJobID = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentJobStatusResult> localVarResponse = GetAsyncJobStatusWithHttpInfo(asyncJobID);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get the status and result of an Extract Document Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>ApiResponse of ExtractDocumentJobStatusResult</returns>
        public Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentJobStatusResult> GetAsyncJobStatusWithHttpInfo(string? asyncJobID = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (asyncJobID != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToMultiMap("", "AsyncJobID", asyncJobID));
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ExtractDocumentJobStatusResult>("/document-ai/document/batch-job/batch-job/status", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAsyncJobStatus", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the status and result of an Extract Document Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtractDocumentJobStatusResult</returns>
        public async System.Threading.Tasks.Task<ExtractDocumentJobStatusResult> GetAsyncJobStatusAsync(string? asyncJobID = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentJobStatusResult> localVarResponse = await GetAsyncJobStatusWithHttpInfoAsync(asyncJobID, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get the status and result of an Extract Document Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtractDocumentJobStatusResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NETCore.DocumentAI.Client.ApiResponse<ExtractDocumentJobStatusResult>> GetAsyncJobStatusWithHttpInfoAsync(string? asyncJobID = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.DocumentAI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (asyncJobID != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cloudmersive.APIClient.NETCore.DocumentAI.Client.ClientUtils.ParameterToMultiMap("", "AsyncJobID", asyncJobID));
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ExtractDocumentJobStatusResult>("/document-ai/document/batch-job/batch-job/status", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAsyncJobStatus", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
