Remove-Item –path ./client –recurse


Invoke-WebRequest -Uri 'https://api.cloudmersive.com/document-ai/docs/v1/swagger' -OutFile '.\documentai-api-swagger.json'
(Get-Content .\documentai-api-swagger.json).replace('localhost', "api.cloudmersive.com") | Set-Content .\documentai-api-swagger.json
(Get-Content .\documentai-api-swagger.json -Raw) -replace '"http"','"https"' | Set-Content .\documentai-api-swagger.json -Encoding UTF8

& java -jar swagger-codegen-cli-2.4.12.jar generate -i .\documentai-api-swagger.json -l csharp -o client -c packageconfig.json
#(Get-Content ./client/src/api/ConvertDocumentApi.js).replace('var returnType = Object;', "var returnType = 'Blob';") | Set-Content ./client/src/api/ConvertDocumentApi.js
#(Get-Content ./client/src/api/ConvertWebApi.js).replace('var returnType = Object;', "var returnType = 'Blob';") | Set-Content ./client/src/api/ConvertWebApi.js
#& npm build ./client






(Get-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj).replace('<Authors>Swagger</Authors>', "<Authors>Cloudmersive</Authors>") | Set-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj
(Get-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj).replace('<Company>Swagger</Company>', "<Company>Cloudmersive</Company>") | Set-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj
(Get-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj).replace('<AssemblyTitle>Swagger Library</AssemblyTitle>', "<AssemblyTitle>Cloudmersive Document AI API Client</AssemblyTitle>") | Set-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj
(Get-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj).replace('<Description>A library generated from a Swagger doc</Description>', "<Description>Document AI APIs let you use AI and Machine Learning to extract data, categories, summaries and insight from free-form text documents.</Description>") | Set-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj
(Get-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj).replace('<TargetFramework>net45</TargetFramework>', "<TargetFramework>netcoreapp2.1</TargetFramework>") | Set-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj
(Get-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj).replace('</PropertyGroup>', "<PackageIconUrl>https://cloudmersive.com/images/cmsdk_core.png</PackageIconUrl><PackageLicenseExpression>Apache-2.0</PackageLicenseExpression><PackageProjectUrl>https://cloudmersive.com/document-ai-api</PackageProjectUrl></PropertyGroup>") | Set-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj
(Get-Content '.\client\src\Cloudmersive.APIClient.NETCore.DocumentAI\Cloudmersive.APIClient.NETCore.DocumentAI.csproj').replace('<PackageReference Include="RestSharp" Version="105.1.0" />', '<PackageReference Include="RestSharp" Version="106.6.10" />') | Set-Content '.\client\src\Cloudmersive.APIClient.NETCore.DocumentAI\Cloudmersive.APIClient.NETCore.DocumentAI.csproj'
(Get-Content '.\client\src\Cloudmersive.APIClient.NETCore.DocumentAI\Client\ApiClient.cs').replace('request.AddFile(param.Value.Name, param.Value.Writer, param.Value.FileName, param.Value.ContentType);', 'request.AddFile(param.Value.Name, param.Value.Writer, param.Value.FileName, param.Value.ContentLength, param.Value.ContentType);') | Set-Content '.\client\src\Cloudmersive.APIClient.NETCore.DocumentAI\Client\ApiClient.cs'


#(Get-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj).replace('</ItemGroup>', '</ItemGroup><Target Name="PostBuild" AfterTargets="PostBuildEvent">    <Exec Command="call powershell C:\CodeSigning\sign.ps1  $(TargetPath)" />  </Target>') | Set-Content ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj

& dotnet build ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj -c Release
& dotnet pack ./client/src/Cloudmersive.APIClient.NETCore.DocumentAI/Cloudmersive.APIClient.NETCore.DocumentAI.csproj -c Release

(Get-Content ./client/README.md).replace(' automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project', " for the [Cloudmersive Document AI API](https://www.cloudmersive.com/document-ai-api)") | Set-Content ./client/README.md

Copy-Item ./client/README.md ./README.md