/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Request to perform an AI document classification on a document
    /// </summary>
    [DataContract]
    public partial class AdvancedExtractClassificationRequest :  IEquatable<AdvancedExtractClassificationRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdvancedExtractClassificationRequest" /> class.
        /// </summary>
        /// <param name="inputFile">Input document file to perform the operation on as a byte array.</param>
        /// <param name="categories">Possible categories for the document.</param>
        /// <param name="preprocessing">Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39;, &#39;SmoothEdges&#39;, &#39;SmoothEdgesPlus&#39;, &#39;Compatability&#39; and &#39;None&#39;.  Default is Auto.  Set to SmoothEdges to smooth harsh edges in the input image to enhance recognition accuracy.  Set to SmoothEdgesPlus to smooth harsh edges to a higher degree.  Set to Compatability for maximum PDF feature compatability..</param>
        /// <param name="resultCrossCheck">Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39;, &#39;Advanced&#39;, &#39;Ultra&#39; and &#39;Hyper&#39;.  Default is None.  Ultra and Hyper will produce the highest accuracy but at the cost of longer processing times..</param>
        /// <param name="maximumPagesProcessed">Optional: Limit the number of pages processed.</param>
        /// <param name="rotateImageDegrees">Optional: Rotate the input image before recognition by the specified number of degrees; valid values range from -360 to +360..</param>
        public AdvancedExtractClassificationRequest(byte[] inputFile = default(byte[]), List<DocumentCategories> categories = default(List<DocumentCategories>), string preprocessing = default(string), string resultCrossCheck = default(string), int? maximumPagesProcessed = default(int?), double? rotateImageDegrees = default(double?))
        {
            this.InputFile = inputFile;
            this.Categories = categories;
            this.Preprocessing = preprocessing;
            this.ResultCrossCheck = resultCrossCheck;
            this.MaximumPagesProcessed = maximumPagesProcessed;
            this.RotateImageDegrees = rotateImageDegrees;
        }
        
        /// <summary>
        /// Input document file to perform the operation on as a byte array
        /// </summary>
        /// <value>Input document file to perform the operation on as a byte array</value>
        [DataMember(Name="InputFile", EmitDefaultValue=false)]
        public byte[] InputFile { get; set; }

        /// <summary>
        /// Possible categories for the document
        /// </summary>
        /// <value>Possible categories for the document</value>
        [DataMember(Name="Categories", EmitDefaultValue=false)]
        public List<DocumentCategories> Categories { get; set; }

        /// <summary>
        /// Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39;, &#39;SmoothEdges&#39;, &#39;SmoothEdgesPlus&#39;, &#39;Compatability&#39; and &#39;None&#39;.  Default is Auto.  Set to SmoothEdges to smooth harsh edges in the input image to enhance recognition accuracy.  Set to SmoothEdgesPlus to smooth harsh edges to a higher degree.  Set to Compatability for maximum PDF feature compatability.
        /// </summary>
        /// <value>Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39;, &#39;SmoothEdges&#39;, &#39;SmoothEdgesPlus&#39;, &#39;Compatability&#39; and &#39;None&#39;.  Default is Auto.  Set to SmoothEdges to smooth harsh edges in the input image to enhance recognition accuracy.  Set to SmoothEdgesPlus to smooth harsh edges to a higher degree.  Set to Compatability for maximum PDF feature compatability.</value>
        [DataMember(Name="Preprocessing", EmitDefaultValue=false)]
        public string Preprocessing { get; set; }

        /// <summary>
        /// Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39;, &#39;Advanced&#39;, &#39;Ultra&#39; and &#39;Hyper&#39;.  Default is None.  Ultra and Hyper will produce the highest accuracy but at the cost of longer processing times.
        /// </summary>
        /// <value>Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39;, &#39;Advanced&#39;, &#39;Ultra&#39; and &#39;Hyper&#39;.  Default is None.  Ultra and Hyper will produce the highest accuracy but at the cost of longer processing times.</value>
        [DataMember(Name="ResultCrossCheck", EmitDefaultValue=false)]
        public string ResultCrossCheck { get; set; }

        /// <summary>
        /// Optional: Limit the number of pages processed
        /// </summary>
        /// <value>Optional: Limit the number of pages processed</value>
        [DataMember(Name="MaximumPagesProcessed", EmitDefaultValue=false)]
        public int? MaximumPagesProcessed { get; set; }

        /// <summary>
        /// Optional: Rotate the input image before recognition by the specified number of degrees; valid values range from -360 to +360.
        /// </summary>
        /// <value>Optional: Rotate the input image before recognition by the specified number of degrees; valid values range from -360 to +360.</value>
        [DataMember(Name="RotateImageDegrees", EmitDefaultValue=false)]
        public double? RotateImageDegrees { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdvancedExtractClassificationRequest {\n");
            sb.Append("  InputFile: ").Append(InputFile).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  Preprocessing: ").Append(Preprocessing).Append("\n");
            sb.Append("  ResultCrossCheck: ").Append(ResultCrossCheck).Append("\n");
            sb.Append("  MaximumPagesProcessed: ").Append(MaximumPagesProcessed).Append("\n");
            sb.Append("  RotateImageDegrees: ").Append(RotateImageDegrees).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AdvancedExtractClassificationRequest);
        }

        /// <summary>
        /// Returns true if AdvancedExtractClassificationRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AdvancedExtractClassificationRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdvancedExtractClassificationRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InputFile == input.InputFile ||
                    (this.InputFile != null &&
                    this.InputFile.Equals(input.InputFile))
                ) && 
                (
                    this.Categories == input.Categories ||
                    this.Categories != null &&
                    this.Categories.SequenceEqual(input.Categories)
                ) && 
                (
                    this.Preprocessing == input.Preprocessing ||
                    (this.Preprocessing != null &&
                    this.Preprocessing.Equals(input.Preprocessing))
                ) && 
                (
                    this.ResultCrossCheck == input.ResultCrossCheck ||
                    (this.ResultCrossCheck != null &&
                    this.ResultCrossCheck.Equals(input.ResultCrossCheck))
                ) && 
                (
                    this.MaximumPagesProcessed == input.MaximumPagesProcessed ||
                    (this.MaximumPagesProcessed != null &&
                    this.MaximumPagesProcessed.Equals(input.MaximumPagesProcessed))
                ) && 
                (
                    this.RotateImageDegrees == input.RotateImageDegrees ||
                    (this.RotateImageDegrees != null &&
                    this.RotateImageDegrees.Equals(input.RotateImageDegrees))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InputFile != null)
                    hashCode = hashCode * 59 + this.InputFile.GetHashCode();
                if (this.Categories != null)
                    hashCode = hashCode * 59 + this.Categories.GetHashCode();
                if (this.Preprocessing != null)
                    hashCode = hashCode * 59 + this.Preprocessing.GetHashCode();
                if (this.ResultCrossCheck != null)
                    hashCode = hashCode * 59 + this.ResultCrossCheck.GetHashCode();
                if (this.MaximumPagesProcessed != null)
                    hashCode = hashCode * 59 + this.MaximumPagesProcessed.GetHashCode();
                if (this.RotateImageDegrees != null)
                    hashCode = hashCode * 59 + this.RotateImageDegrees.GetHashCode();
                return hashCode;
            }
        }
    }

}
