/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Answer to an input question
    /// </summary>
    [DataContract]
    public partial class DocumentQuestionAnswerItem :  IEquatable<DocumentQuestionAnswerItem>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentQuestionAnswerItem" /> class.
        /// </summary>
        /// <param name="questionId">ID of the input question.</param>
        /// <param name="answerValue">Answer response value, formatted as a string, for this question.  Boolean questions will return YES or NO..</param>
        /// <param name="answerRationale">Rationale explaining why this answer was given.</param>
        /// <param name="confidenceScore">Confidence score between 0.0 and 1.0 where values above 0.8 indicate high confidence.</param>
        public DocumentQuestionAnswerItem(string questionId = default(string), string answerValue = default(string), string answerRationale = default(string), double? confidenceScore = default(double?))
        {
            this.QuestionId = questionId;
            this.AnswerValue = answerValue;
            this.AnswerRationale = answerRationale;
            this.ConfidenceScore = confidenceScore;
        }
        
        /// <summary>
        /// ID of the input question
        /// </summary>
        /// <value>ID of the input question</value>
        [DataMember(Name="QuestionId", EmitDefaultValue=false)]
        public string QuestionId { get; set; }

        /// <summary>
        /// Answer response value, formatted as a string, for this question.  Boolean questions will return YES or NO.
        /// </summary>
        /// <value>Answer response value, formatted as a string, for this question.  Boolean questions will return YES or NO.</value>
        [DataMember(Name="AnswerValue", EmitDefaultValue=false)]
        public string AnswerValue { get; set; }

        /// <summary>
        /// Rationale explaining why this answer was given
        /// </summary>
        /// <value>Rationale explaining why this answer was given</value>
        [DataMember(Name="AnswerRationale", EmitDefaultValue=false)]
        public string AnswerRationale { get; set; }

        /// <summary>
        /// Confidence score between 0.0 and 1.0 where values above 0.8 indicate high confidence
        /// </summary>
        /// <value>Confidence score between 0.0 and 1.0 where values above 0.8 indicate high confidence</value>
        [DataMember(Name="ConfidenceScore", EmitDefaultValue=false)]
        public double? ConfidenceScore { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentQuestionAnswerItem {\n");
            sb.Append("  QuestionId: ").Append(QuestionId).Append("\n");
            sb.Append("  AnswerValue: ").Append(AnswerValue).Append("\n");
            sb.Append("  AnswerRationale: ").Append(AnswerRationale).Append("\n");
            sb.Append("  ConfidenceScore: ").Append(ConfidenceScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocumentQuestionAnswerItem);
        }

        /// <summary>
        /// Returns true if DocumentQuestionAnswerItem instances are equal
        /// </summary>
        /// <param name="input">Instance of DocumentQuestionAnswerItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentQuestionAnswerItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QuestionId == input.QuestionId ||
                    (this.QuestionId != null &&
                    this.QuestionId.Equals(input.QuestionId))
                ) && 
                (
                    this.AnswerValue == input.AnswerValue ||
                    (this.AnswerValue != null &&
                    this.AnswerValue.Equals(input.AnswerValue))
                ) && 
                (
                    this.AnswerRationale == input.AnswerRationale ||
                    (this.AnswerRationale != null &&
                    this.AnswerRationale.Equals(input.AnswerRationale))
                ) && 
                (
                    this.ConfidenceScore == input.ConfidenceScore ||
                    (this.ConfidenceScore != null &&
                    this.ConfidenceScore.Equals(input.ConfidenceScore))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QuestionId != null)
                    hashCode = hashCode * 59 + this.QuestionId.GetHashCode();
                if (this.AnswerValue != null)
                    hashCode = hashCode * 59 + this.AnswerValue.GetHashCode();
                if (this.AnswerRationale != null)
                    hashCode = hashCode * 59 + this.AnswerRationale.GetHashCode();
                if (this.ConfidenceScore != null)
                    hashCode = hashCode * 59 + this.ConfidenceScore.GetHashCode();
                return hashCode;
            }
        }
    }

}
