/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Result of performing a document policy enforcement operation
    /// </summary>
    [DataContract(Name = "DocumentPolicyResult")]
    public partial class DocumentPolicyResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentPolicyResult" /> class.
        /// </summary>
        /// <param name="cleanResult">True if the document complies with all of the policies, and false if it does not.</param>
        /// <param name="riskScore">Risk score between 0.0 and 1.0 where values above 0.5 are increasing levels of risk.</param>
        /// <param name="ruleViolations">Policy violations.</param>
        public DocumentPolicyResult(bool cleanResult = default, double riskScore = default, List<PolicyRuleViolation> ruleViolations = default)
        {
            this.CleanResult = cleanResult;
            this.RiskScore = riskScore;
            this.RuleViolations = ruleViolations;
        }

        /// <summary>
        /// True if the document complies with all of the policies, and false if it does not
        /// </summary>
        /// <value>True if the document complies with all of the policies, and false if it does not</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Risk score between 0.0 and 1.0 where values above 0.5 are increasing levels of risk
        /// </summary>
        /// <value>Risk score between 0.0 and 1.0 where values above 0.5 are increasing levels of risk</value>
        [DataMember(Name = "RiskScore", EmitDefaultValue = false)]
        public double RiskScore { get; set; }

        /// <summary>
        /// Policy violations
        /// </summary>
        /// <value>Policy violations</value>
        [DataMember(Name = "RuleViolations", EmitDefaultValue = false)]
        public List<PolicyRuleViolation> RuleViolations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentPolicyResult {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  RiskScore: ").Append(RiskScore).Append("\n");
            sb.Append("  RuleViolations: ").Append(RuleViolations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
