/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Result of classifying a document using AI
    /// </summary>
    [DataContract]
    public partial class DocumentClassificationResult :  IEquatable<DocumentClassificationResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentClassificationResult" /> class.
        /// </summary>
        /// <param name="successful">True if successful, false otherwise.</param>
        /// <param name="documentCategoryResult">Category applied to the document; if a category could not be identified then \&quot;other\&quot; will be used.  Spaces are replaced with underscores..</param>
        public DocumentClassificationResult(bool? successful = default(bool?), string documentCategoryResult = default(string))
        {
            this.Successful = successful;
            this.DocumentCategoryResult = documentCategoryResult;
        }
        
        /// <summary>
        /// True if successful, false otherwise
        /// </summary>
        /// <value>True if successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// Category applied to the document; if a category could not be identified then \&quot;other\&quot; will be used.  Spaces are replaced with underscores.
        /// </summary>
        /// <value>Category applied to the document; if a category could not be identified then \&quot;other\&quot; will be used.  Spaces are replaced with underscores.</value>
        [DataMember(Name="DocumentCategoryResult", EmitDefaultValue=false)]
        public string DocumentCategoryResult { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentClassificationResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  DocumentCategoryResult: ").Append(DocumentCategoryResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocumentClassificationResult);
        }

        /// <summary>
        /// Returns true if DocumentClassificationResult instances are equal
        /// </summary>
        /// <param name="input">Instance of DocumentClassificationResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentClassificationResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.DocumentCategoryResult == input.DocumentCategoryResult ||
                    (this.DocumentCategoryResult != null &&
                    this.DocumentCategoryResult.Equals(input.DocumentCategoryResult))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.DocumentCategoryResult != null)
                    hashCode = hashCode * 59 + this.DocumentCategoryResult.GetHashCode();
                return hashCode;
            }
        }
    }

}
