/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// DocumentQuestionsRequest
    /// </summary>
    [DataContract(Name = "DocumentQuestionsRequest")]
    public partial class DocumentQuestionsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentQuestionsRequest" /> class.
        /// </summary>
        /// <param name="inputFile">Input file as a byte array.</param>
        /// <param name="questionsYesNo">Optional: Yes or No boolean questions to answer about the document.</param>
        /// <param name="questionsMultipleChoice">Optional: Multiple choice questions to answer about the document.</param>
        /// <param name="questionsFreeResponse">Optional: Free response questions to answer about the document.</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images.</param>
        public DocumentQuestionsRequest(byte[] inputFile = default, List<DocumentQuestionBoolean> questionsYesNo = default, List<DocumentQuestionMultipleChoice> questionsMultipleChoice = default, List<DocumentQuestionFreeResponse> questionsFreeResponse = default, string recognitionMode = default)
        {
            this.InputFile = inputFile;
            this.QuestionsYesNo = questionsYesNo;
            this.QuestionsMultipleChoice = questionsMultipleChoice;
            this.QuestionsFreeResponse = questionsFreeResponse;
            this.RecognitionMode = recognitionMode;
        }

        /// <summary>
        /// Input file as a byte array
        /// </summary>
        /// <value>Input file as a byte array</value>
        [DataMember(Name = "InputFile", EmitDefaultValue = false)]
        public byte[] InputFile { get; set; }

        /// <summary>
        /// Optional: Yes or No boolean questions to answer about the document
        /// </summary>
        /// <value>Optional: Yes or No boolean questions to answer about the document</value>
        [DataMember(Name = "QuestionsYesNo", EmitDefaultValue = false)]
        public List<DocumentQuestionBoolean> QuestionsYesNo { get; set; }

        /// <summary>
        /// Optional: Multiple choice questions to answer about the document
        /// </summary>
        /// <value>Optional: Multiple choice questions to answer about the document</value>
        [DataMember(Name = "QuestionsMultipleChoice", EmitDefaultValue = false)]
        public List<DocumentQuestionMultipleChoice> QuestionsMultipleChoice { get; set; }

        /// <summary>
        /// Optional: Free response questions to answer about the document
        /// </summary>
        /// <value>Optional: Free response questions to answer about the document</value>
        [DataMember(Name = "QuestionsFreeResponse", EmitDefaultValue = false)]
        public List<DocumentQuestionFreeResponse> QuestionsFreeResponse { get; set; }

        /// <summary>
        /// Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
        /// </summary>
        /// <value>Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images</value>
        [DataMember(Name = "RecognitionMode", EmitDefaultValue = false)]
        public string RecognitionMode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentQuestionsRequest {\n");
            sb.Append("  InputFile: ").Append(InputFile).Append("\n");
            sb.Append("  QuestionsYesNo: ").Append(QuestionsYesNo).Append("\n");
            sb.Append("  QuestionsMultipleChoice: ").Append(QuestionsMultipleChoice).Append("\n");
            sb.Append("  QuestionsFreeResponse: ").Append(QuestionsFreeResponse).Append("\n");
            sb.Append("  RecognitionMode: ").Append(RecognitionMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
