/* 
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// DocumentQuestionsRequest
    /// </summary>
    [DataContract]
    public partial class DocumentQuestionsRequest :  IEquatable<DocumentQuestionsRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentQuestionsRequest" /> class.
        /// </summary>
        /// <param name="inputFile">Input file as a byte array.</param>
        /// <param name="questionsYesNo">Optional: Yes or No boolean questions to answer about the document.</param>
        /// <param name="questionsMultipleChoice">Optional: Multiple choice questions to answer about the document.</param>
        /// <param name="questionsFreeResponse">Optional: Free response questions to answer about the document.</param>
        /// <param name="recognitionMode">Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images.</param>
        public DocumentQuestionsRequest(byte[] inputFile = default(byte[]), List<DocumentQuestionBoolean> questionsYesNo = default(List<DocumentQuestionBoolean>), List<DocumentQuestionMultipleChoice> questionsMultipleChoice = default(List<DocumentQuestionMultipleChoice>), List<DocumentQuestionFreeResponse> questionsFreeResponse = default(List<DocumentQuestionFreeResponse>), string recognitionMode = default(string))
        {
            this.InputFile = inputFile;
            this.QuestionsYesNo = questionsYesNo;
            this.QuestionsMultipleChoice = questionsMultipleChoice;
            this.QuestionsFreeResponse = questionsFreeResponse;
            this.RecognitionMode = recognitionMode;
        }
        
        /// <summary>
        /// Input file as a byte array
        /// </summary>
        /// <value>Input file as a byte array</value>
        [DataMember(Name="InputFile", EmitDefaultValue=false)]
        public byte[] InputFile { get; set; }

        /// <summary>
        /// Optional: Yes or No boolean questions to answer about the document
        /// </summary>
        /// <value>Optional: Yes or No boolean questions to answer about the document</value>
        [DataMember(Name="QuestionsYesNo", EmitDefaultValue=false)]
        public List<DocumentQuestionBoolean> QuestionsYesNo { get; set; }

        /// <summary>
        /// Optional: Multiple choice questions to answer about the document
        /// </summary>
        /// <value>Optional: Multiple choice questions to answer about the document</value>
        [DataMember(Name="QuestionsMultipleChoice", EmitDefaultValue=false)]
        public List<DocumentQuestionMultipleChoice> QuestionsMultipleChoice { get; set; }

        /// <summary>
        /// Optional: Free response questions to answer about the document
        /// </summary>
        /// <value>Optional: Free response questions to answer about the document</value>
        [DataMember(Name="QuestionsFreeResponse", EmitDefaultValue=false)]
        public List<DocumentQuestionFreeResponse> QuestionsFreeResponse { get; set; }

        /// <summary>
        /// Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
        /// </summary>
        /// <value>Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images</value>
        [DataMember(Name="RecognitionMode", EmitDefaultValue=false)]
        public string RecognitionMode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentQuestionsRequest {\n");
            sb.Append("  InputFile: ").Append(InputFile).Append("\n");
            sb.Append("  QuestionsYesNo: ").Append(QuestionsYesNo).Append("\n");
            sb.Append("  QuestionsMultipleChoice: ").Append(QuestionsMultipleChoice).Append("\n");
            sb.Append("  QuestionsFreeResponse: ").Append(QuestionsFreeResponse).Append("\n");
            sb.Append("  RecognitionMode: ").Append(RecognitionMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocumentQuestionsRequest);
        }

        /// <summary>
        /// Returns true if DocumentQuestionsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DocumentQuestionsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentQuestionsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InputFile == input.InputFile ||
                    (this.InputFile != null &&
                    this.InputFile.Equals(input.InputFile))
                ) && 
                (
                    this.QuestionsYesNo == input.QuestionsYesNo ||
                    this.QuestionsYesNo != null &&
                    this.QuestionsYesNo.SequenceEqual(input.QuestionsYesNo)
                ) && 
                (
                    this.QuestionsMultipleChoice == input.QuestionsMultipleChoice ||
                    this.QuestionsMultipleChoice != null &&
                    this.QuestionsMultipleChoice.SequenceEqual(input.QuestionsMultipleChoice)
                ) && 
                (
                    this.QuestionsFreeResponse == input.QuestionsFreeResponse ||
                    this.QuestionsFreeResponse != null &&
                    this.QuestionsFreeResponse.SequenceEqual(input.QuestionsFreeResponse)
                ) && 
                (
                    this.RecognitionMode == input.RecognitionMode ||
                    (this.RecognitionMode != null &&
                    this.RecognitionMode.Equals(input.RecognitionMode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InputFile != null)
                    hashCode = hashCode * 59 + this.InputFile.GetHashCode();
                if (this.QuestionsYesNo != null)
                    hashCode = hashCode * 59 + this.QuestionsYesNo.GetHashCode();
                if (this.QuestionsMultipleChoice != null)
                    hashCode = hashCode * 59 + this.QuestionsMultipleChoice.GetHashCode();
                if (this.QuestionsFreeResponse != null)
                    hashCode = hashCode * 59 + this.QuestionsFreeResponse.GetHashCode();
                if (this.RecognitionMode != null)
                    hashCode = hashCode * 59 + this.RecognitionMode.GetHashCode();
                return hashCode;
            }
        }
    }

}
