/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Multiple choice question
    /// </summary>
    [DataContract]
    public partial class DocumentQuestionMultipleChoice :  IEquatable<DocumentQuestionMultipleChoice>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentQuestionMultipleChoice" /> class.
        /// </summary>
        /// <param name="questionId">Unique ID of the question, e.g. 1 or 2A.</param>
        /// <param name="questionText">Question in natural language to ask of the document where the answer resolves to one of a fixed number of provided choices, e.g. &#39;What is the governing law of this agreement?&#39;.</param>
        /// <param name="responseChoices">Possible response choices for the multiple-choice question.</param>
        public DocumentQuestionMultipleChoice(string questionId = default(string), string questionText = default(string), List<DocumentQuestionChoiceItem> responseChoices = default(List<DocumentQuestionChoiceItem>))
        {
            this.QuestionId = questionId;
            this.QuestionText = questionText;
            this.ResponseChoices = responseChoices;
        }
        
        /// <summary>
        /// Unique ID of the question, e.g. 1 or 2A
        /// </summary>
        /// <value>Unique ID of the question, e.g. 1 or 2A</value>
        [DataMember(Name="QuestionId", EmitDefaultValue=false)]
        public string QuestionId { get; set; }

        /// <summary>
        /// Question in natural language to ask of the document where the answer resolves to one of a fixed number of provided choices, e.g. &#39;What is the governing law of this agreement?&#39;
        /// </summary>
        /// <value>Question in natural language to ask of the document where the answer resolves to one of a fixed number of provided choices, e.g. &#39;What is the governing law of this agreement?&#39;</value>
        [DataMember(Name="QuestionText", EmitDefaultValue=false)]
        public string QuestionText { get; set; }

        /// <summary>
        /// Possible response choices for the multiple-choice question
        /// </summary>
        /// <value>Possible response choices for the multiple-choice question</value>
        [DataMember(Name="ResponseChoices", EmitDefaultValue=false)]
        public List<DocumentQuestionChoiceItem> ResponseChoices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentQuestionMultipleChoice {\n");
            sb.Append("  QuestionId: ").Append(QuestionId).Append("\n");
            sb.Append("  QuestionText: ").Append(QuestionText).Append("\n");
            sb.Append("  ResponseChoices: ").Append(ResponseChoices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocumentQuestionMultipleChoice);
        }

        /// <summary>
        /// Returns true if DocumentQuestionMultipleChoice instances are equal
        /// </summary>
        /// <param name="input">Instance of DocumentQuestionMultipleChoice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentQuestionMultipleChoice input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QuestionId == input.QuestionId ||
                    (this.QuestionId != null &&
                    this.QuestionId.Equals(input.QuestionId))
                ) && 
                (
                    this.QuestionText == input.QuestionText ||
                    (this.QuestionText != null &&
                    this.QuestionText.Equals(input.QuestionText))
                ) && 
                (
                    this.ResponseChoices == input.ResponseChoices ||
                    this.ResponseChoices != null &&
                    this.ResponseChoices.SequenceEqual(input.ResponseChoices)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QuestionId != null)
                    hashCode = hashCode * 59 + this.QuestionId.GetHashCode();
                if (this.QuestionText != null)
                    hashCode = hashCode * 59 + this.QuestionText.GetHashCode();
                if (this.ResponseChoices != null)
                    hashCode = hashCode * 59 + this.ResponseChoices.GetHashCode();
                return hashCode;
            }
        }
    }

}
