/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Possible response choice for a multiple-choice question
    /// </summary>
    [DataContract]
    public partial class DocumentQuestionChoiceItem :  IEquatable<DocumentQuestionChoiceItem>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentQuestionChoiceItem" /> class.
        /// </summary>
        /// <param name="choiceId">Unique ID of the response choice, e.g. 3C.</param>
        /// <param name="choiceText">Description text of this choice, e.g. &#39;Delaware&#39;.</param>
        public DocumentQuestionChoiceItem(string choiceId = default(string), string choiceText = default(string))
        {
            this.ChoiceId = choiceId;
            this.ChoiceText = choiceText;
        }
        
        /// <summary>
        /// Unique ID of the response choice, e.g. 3C
        /// </summary>
        /// <value>Unique ID of the response choice, e.g. 3C</value>
        [DataMember(Name="ChoiceId", EmitDefaultValue=false)]
        public string ChoiceId { get; set; }

        /// <summary>
        /// Description text of this choice, e.g. &#39;Delaware&#39;
        /// </summary>
        /// <value>Description text of this choice, e.g. &#39;Delaware&#39;</value>
        [DataMember(Name="ChoiceText", EmitDefaultValue=false)]
        public string ChoiceText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentQuestionChoiceItem {\n");
            sb.Append("  ChoiceId: ").Append(ChoiceId).Append("\n");
            sb.Append("  ChoiceText: ").Append(ChoiceText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocumentQuestionChoiceItem);
        }

        /// <summary>
        /// Returns true if DocumentQuestionChoiceItem instances are equal
        /// </summary>
        /// <param name="input">Instance of DocumentQuestionChoiceItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentQuestionChoiceItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ChoiceId == input.ChoiceId ||
                    (this.ChoiceId != null &&
                    this.ChoiceId.Equals(input.ChoiceId))
                ) && 
                (
                    this.ChoiceText == input.ChoiceText ||
                    (this.ChoiceText != null &&
                    this.ChoiceText.Equals(input.ChoiceText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ChoiceId != null)
                    hashCode = hashCode * 59 + this.ChoiceId.GetHashCode();
                if (this.ChoiceText != null)
                    hashCode = hashCode * 59 + this.ChoiceText.GetHashCode();
                return hashCode;
            }
        }
    }

}
