/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Multiple choice question
    /// </summary>
    [DataContract(Name = "DocumentQuestionMultipleChoice")]
    public partial class DocumentQuestionMultipleChoice : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentQuestionMultipleChoice" /> class.
        /// </summary>
        /// <param name="questionId">Unique ID of the question, e.g. 1 or 2A.</param>
        /// <param name="questionText">Question in natural language to ask of the document where the answer resolves to one of a fixed number of provided choices, e.g. &#39;What is the governing law of this agreement?&#39;.</param>
        /// <param name="responseChoices">Possible response choices for the multiple-choice question.</param>
        public DocumentQuestionMultipleChoice(string questionId = default, string questionText = default, List<DocumentQuestionChoiceItem> responseChoices = default)
        {
            this.QuestionId = questionId;
            this.QuestionText = questionText;
            this.ResponseChoices = responseChoices;
        }

        /// <summary>
        /// Unique ID of the question, e.g. 1 or 2A
        /// </summary>
        /// <value>Unique ID of the question, e.g. 1 or 2A</value>
        [DataMember(Name = "QuestionId", EmitDefaultValue = false)]
        public string QuestionId { get; set; }

        /// <summary>
        /// Question in natural language to ask of the document where the answer resolves to one of a fixed number of provided choices, e.g. &#39;What is the governing law of this agreement?&#39;
        /// </summary>
        /// <value>Question in natural language to ask of the document where the answer resolves to one of a fixed number of provided choices, e.g. &#39;What is the governing law of this agreement?&#39;</value>
        [DataMember(Name = "QuestionText", EmitDefaultValue = false)]
        public string QuestionText { get; set; }

        /// <summary>
        /// Possible response choices for the multiple-choice question
        /// </summary>
        /// <value>Possible response choices for the multiple-choice question</value>
        [DataMember(Name = "ResponseChoices", EmitDefaultValue = false)]
        public List<DocumentQuestionChoiceItem> ResponseChoices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentQuestionMultipleChoice {\n");
            sb.Append("  QuestionId: ").Append(QuestionId).Append("\n");
            sb.Append("  QuestionText: ").Append(QuestionText).Append("\n");
            sb.Append("  ResponseChoices: ").Append(ResponseChoices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
