/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Result of performing a document question answering operation
    /// </summary>
    [DataContract(Name = "DocumentQuestionAnswersResult")]
    public partial class DocumentQuestionAnswersResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentQuestionAnswersResult" /> class.
        /// </summary>
        /// <param name="successful">True if the operation was completed successfully, or false otherwise.</param>
        /// <param name="confidenceScore">Confidence score between 0.0 and 1.0 where values above 0.8 indicate high confidence.</param>
        /// <param name="answerResults">answerResults.</param>
        public DocumentQuestionAnswersResult(bool successful = default, double confidenceScore = default, List<DocumentQuestionAnswerItem> answerResults = default)
        {
            this.Successful = successful;
            this.ConfidenceScore = confidenceScore;
            this.AnswerResults = answerResults;
        }

        /// <summary>
        /// True if the operation was completed successfully, or false otherwise
        /// </summary>
        /// <value>True if the operation was completed successfully, or false otherwise</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// Confidence score between 0.0 and 1.0 where values above 0.8 indicate high confidence
        /// </summary>
        /// <value>Confidence score between 0.0 and 1.0 where values above 0.8 indicate high confidence</value>
        [DataMember(Name = "ConfidenceScore", EmitDefaultValue = false)]
        public double ConfidenceScore { get; set; }

        /// <summary>
        /// Gets or Sets AnswerResults
        /// </summary>
        [DataMember(Name = "AnswerResults", EmitDefaultValue = false)]
        public List<DocumentQuestionAnswerItem> AnswerResults { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentQuestionAnswersResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  ConfidenceScore: ").Append(ConfidenceScore).Append("\n");
            sb.Append("  AnswerResults: ").Append(AnswerResults).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
