/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Extracted barcode result
    /// </summary>
    [DataContract]
    public partial class ExtractedBarcodeItem :  IEquatable<ExtractedBarcodeItem>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractedBarcodeItem" /> class.
        /// </summary>
        /// <param name="barcodeType">Type of the barcode identified, possible values are: AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB, UNKNOWN.</param>
        /// <param name="barcodeValue">Value of the barcode as a string.</param>
        public ExtractedBarcodeItem(string barcodeType = default(string), string barcodeValue = default(string))
        {
            this.BarcodeType = barcodeType;
            this.BarcodeValue = barcodeValue;
        }
        
        /// <summary>
        /// Type of the barcode identified, possible values are: AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB, UNKNOWN
        /// </summary>
        /// <value>Type of the barcode identified, possible values are: AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB, UNKNOWN</value>
        [DataMember(Name="BarcodeType", EmitDefaultValue=false)]
        public string BarcodeType { get; set; }

        /// <summary>
        /// Value of the barcode as a string
        /// </summary>
        /// <value>Value of the barcode as a string</value>
        [DataMember(Name="BarcodeValue", EmitDefaultValue=false)]
        public string BarcodeValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExtractedBarcodeItem {\n");
            sb.Append("  BarcodeType: ").Append(BarcodeType).Append("\n");
            sb.Append("  BarcodeValue: ").Append(BarcodeValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExtractedBarcodeItem);
        }

        /// <summary>
        /// Returns true if ExtractedBarcodeItem instances are equal
        /// </summary>
        /// <param name="input">Instance of ExtractedBarcodeItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExtractedBarcodeItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BarcodeType == input.BarcodeType ||
                    (this.BarcodeType != null &&
                    this.BarcodeType.Equals(input.BarcodeType))
                ) && 
                (
                    this.BarcodeValue == input.BarcodeValue ||
                    (this.BarcodeValue != null &&
                    this.BarcodeValue.Equals(input.BarcodeValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BarcodeType != null)
                    hashCode = hashCode * 59 + this.BarcodeType.GetHashCode();
                if (this.BarcodeValue != null)
                    hashCode = hashCode * 59 + this.BarcodeValue.GetHashCode();
                return hashCode;
            }
        }
    }

}
