/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Result of extracting text from a document
    /// </summary>
    [DataContract]
    public partial class ExtractTextResponse :  IEquatable<ExtractTextResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractTextResponse" /> class.
        /// </summary>
        /// <param name="successful">True if successful, false otherwise.</param>
        /// <param name="pageResults">Page results from the extraction operation.</param>
        public ExtractTextResponse(bool? successful = default(bool?), List<ExtractedTextPage> pageResults = default(List<ExtractedTextPage>))
        {
            this.Successful = successful;
            this.PageResults = pageResults;
        }
        
        /// <summary>
        /// True if successful, false otherwise
        /// </summary>
        /// <value>True if successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// Page results from the extraction operation
        /// </summary>
        /// <value>Page results from the extraction operation</value>
        [DataMember(Name="PageResults", EmitDefaultValue=false)]
        public List<ExtractedTextPage> PageResults { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExtractTextResponse {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  PageResults: ").Append(PageResults).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExtractTextResponse);
        }

        /// <summary>
        /// Returns true if ExtractTextResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ExtractTextResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExtractTextResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.PageResults == input.PageResults ||
                    this.PageResults != null &&
                    this.PageResults.SequenceEqual(input.PageResults)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.PageResults != null)
                    hashCode = hashCode * 59 + this.PageResults.GetHashCode();
                return hashCode;
            }
        }
    }

}
