/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Result of extracting fields from a document
    /// </summary>
    [DataContract]
    public partial class ExtractFieldsAndTablesResponse :  IEquatable<ExtractFieldsAndTablesResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractFieldsAndTablesResponse" /> class.
        /// </summary>
        /// <param name="successful">True if successful, false otherwise.</param>
        /// <param name="fieldResults">Field value results from the extraction operation.</param>
        /// <param name="tableResults">Table value results from the extraction operation.</param>
        public ExtractFieldsAndTablesResponse(bool? successful = default(bool?), List<FieldValue> fieldResults = default(List<FieldValue>), List<TableResult> tableResults = default(List<TableResult>))
        {
            this.Successful = successful;
            this.FieldResults = fieldResults;
            this.TableResults = tableResults;
        }
        
        /// <summary>
        /// True if successful, false otherwise
        /// </summary>
        /// <value>True if successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// Field value results from the extraction operation
        /// </summary>
        /// <value>Field value results from the extraction operation</value>
        [DataMember(Name="FieldResults", EmitDefaultValue=false)]
        public List<FieldValue> FieldResults { get; set; }

        /// <summary>
        /// Table value results from the extraction operation
        /// </summary>
        /// <value>Table value results from the extraction operation</value>
        [DataMember(Name="TableResults", EmitDefaultValue=false)]
        public List<TableResult> TableResults { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExtractFieldsAndTablesResponse {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  FieldResults: ").Append(FieldResults).Append("\n");
            sb.Append("  TableResults: ").Append(TableResults).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExtractFieldsAndTablesResponse);
        }

        /// <summary>
        /// Returns true if ExtractFieldsAndTablesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ExtractFieldsAndTablesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExtractFieldsAndTablesResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.FieldResults == input.FieldResults ||
                    this.FieldResults != null &&
                    this.FieldResults.SequenceEqual(input.FieldResults)
                ) && 
                (
                    this.TableResults == input.TableResults ||
                    this.TableResults != null &&
                    this.TableResults.SequenceEqual(input.TableResults)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.FieldResults != null)
                    hashCode = hashCode * 59 + this.FieldResults.GetHashCode();
                if (this.TableResults != null)
                    hashCode = hashCode * 59 + this.TableResults.GetHashCode();
                return hashCode;
            }
        }
    }

}
