/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Result of performing a batch job operation
    /// </summary>
    [DataContract(Name = "ExtractDocumentJobStatusResult")]
    public partial class ExtractDocumentJobStatusResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractDocumentJobStatusResult" /> class.
        /// </summary>
        /// <param name="successful">True if the operation to check the status of the job was successful, false otherwise.</param>
        /// <param name="asyncJobStatus">Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED.</param>
        /// <param name="asyncJobID">Job ID.</param>
        /// <param name="extractTextResult">extractTextResult.</param>
        /// <param name="extractFieldsAndTablesResult">extractFieldsAndTablesResult.</param>
        /// <param name="extractFieldsResult">extractFieldsResult.</param>
        /// <param name="extractClassificationResult">extractClassificationResult.</param>
        /// <param name="errorMessage">Error message (if any).</param>
        public ExtractDocumentJobStatusResult(bool successful = default, string asyncJobStatus = default, string asyncJobID = default, ExtractTextResponse extractTextResult = default, ExtractFieldsAndTablesResponse extractFieldsAndTablesResult = default, ExtractFieldsResponse extractFieldsResult = default, DocumentClassificationResult extractClassificationResult = default, string errorMessage = default)
        {
            this.Successful = successful;
            this.AsyncJobStatus = asyncJobStatus;
            this.AsyncJobID = asyncJobID;
            this.ExtractTextResult = extractTextResult;
            this.ExtractFieldsAndTablesResult = extractFieldsAndTablesResult;
            this.ExtractFieldsResult = extractFieldsResult;
            this.ExtractClassificationResult = extractClassificationResult;
            this.ErrorMessage = errorMessage;
        }

        /// <summary>
        /// True if the operation to check the status of the job was successful, false otherwise
        /// </summary>
        /// <value>True if the operation to check the status of the job was successful, false otherwise</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED
        /// </summary>
        /// <value>Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED</value>
        [DataMember(Name = "AsyncJobStatus", EmitDefaultValue = false)]
        public string AsyncJobStatus { get; set; }

        /// <summary>
        /// Job ID
        /// </summary>
        /// <value>Job ID</value>
        [DataMember(Name = "AsyncJobID", EmitDefaultValue = false)]
        public string AsyncJobID { get; set; }

        /// <summary>
        /// Gets or Sets ExtractTextResult
        /// </summary>
        [DataMember(Name = "ExtractTextResult", EmitDefaultValue = false)]
        public ExtractTextResponse ExtractTextResult { get; set; }

        /// <summary>
        /// Gets or Sets ExtractFieldsAndTablesResult
        /// </summary>
        [DataMember(Name = "ExtractFieldsAndTablesResult", EmitDefaultValue = false)]
        public ExtractFieldsAndTablesResponse ExtractFieldsAndTablesResult { get; set; }

        /// <summary>
        /// Gets or Sets ExtractFieldsResult
        /// </summary>
        [DataMember(Name = "ExtractFieldsResult", EmitDefaultValue = false)]
        public ExtractFieldsResponse ExtractFieldsResult { get; set; }

        /// <summary>
        /// Gets or Sets ExtractClassificationResult
        /// </summary>
        [DataMember(Name = "ExtractClassificationResult", EmitDefaultValue = false)]
        public DocumentClassificationResult ExtractClassificationResult { get; set; }

        /// <summary>
        /// Error message (if any)
        /// </summary>
        /// <value>Error message (if any)</value>
        [DataMember(Name = "ErrorMessage", EmitDefaultValue = false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExtractDocumentJobStatusResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  AsyncJobStatus: ").Append(AsyncJobStatus).Append("\n");
            sb.Append("  AsyncJobID: ").Append(AsyncJobID).Append("\n");
            sb.Append("  ExtractTextResult: ").Append(ExtractTextResult).Append("\n");
            sb.Append("  ExtractFieldsAndTablesResult: ").Append(ExtractFieldsAndTablesResult).Append("\n");
            sb.Append("  ExtractFieldsResult: ").Append(ExtractFieldsResult).Append("\n");
            sb.Append("  ExtractClassificationResult: ").Append(ExtractClassificationResult).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
