/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Field value result of extracting fields from a document
    /// </summary>
    [DataContract]
    public partial class FieldValue :  IEquatable<FieldValue>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldValue" /> class.
        /// </summary>
        /// <param name="fieldName">Name of the field (note that spaces will be replaced with underscore).</param>
        /// <param name="fieldStringValue">Primary or first string value of the field that was extractged from the document.</param>
        /// <param name="additionalFieldStringValues">Additional values for this field when the same field is present with multiple values, for example, if two instances of the same form occur in the same document.</param>
        public FieldValue(string fieldName = default(string), string fieldStringValue = default(string), List<string> additionalFieldStringValues = default(List<string>))
        {
            this.FieldName = fieldName;
            this.FieldStringValue = fieldStringValue;
            this.AdditionalFieldStringValues = additionalFieldStringValues;
        }
        
        /// <summary>
        /// Name of the field (note that spaces will be replaced with underscore)
        /// </summary>
        /// <value>Name of the field (note that spaces will be replaced with underscore)</value>
        [DataMember(Name="FieldName", EmitDefaultValue=false)]
        public string FieldName { get; set; }

        /// <summary>
        /// Primary or first string value of the field that was extractged from the document
        /// </summary>
        /// <value>Primary or first string value of the field that was extractged from the document</value>
        [DataMember(Name="FieldStringValue", EmitDefaultValue=false)]
        public string FieldStringValue { get; set; }

        /// <summary>
        /// Additional values for this field when the same field is present with multiple values, for example, if two instances of the same form occur in the same document
        /// </summary>
        /// <value>Additional values for this field when the same field is present with multiple values, for example, if two instances of the same form occur in the same document</value>
        [DataMember(Name="AdditionalFieldStringValues", EmitDefaultValue=false)]
        public List<string> AdditionalFieldStringValues { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FieldValue {\n");
            sb.Append("  FieldName: ").Append(FieldName).Append("\n");
            sb.Append("  FieldStringValue: ").Append(FieldStringValue).Append("\n");
            sb.Append("  AdditionalFieldStringValues: ").Append(AdditionalFieldStringValues).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FieldValue);
        }

        /// <summary>
        /// Returns true if FieldValue instances are equal
        /// </summary>
        /// <param name="input">Instance of FieldValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FieldValue input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FieldName == input.FieldName ||
                    (this.FieldName != null &&
                    this.FieldName.Equals(input.FieldName))
                ) && 
                (
                    this.FieldStringValue == input.FieldStringValue ||
                    (this.FieldStringValue != null &&
                    this.FieldStringValue.Equals(input.FieldStringValue))
                ) && 
                (
                    this.AdditionalFieldStringValues == input.AdditionalFieldStringValues ||
                    this.AdditionalFieldStringValues != null &&
                    this.AdditionalFieldStringValues.SequenceEqual(input.AdditionalFieldStringValues)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FieldName != null)
                    hashCode = hashCode * 59 + this.FieldName.GetHashCode();
                if (this.FieldStringValue != null)
                    hashCode = hashCode * 59 + this.FieldStringValue.GetHashCode();
                if (this.AdditionalFieldStringValues != null)
                    hashCode = hashCode * 59 + this.AdditionalFieldStringValues.GetHashCode();
                return hashCode;
            }
        }
    }

}
