/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Field value result of extracting fields from a document
    /// </summary>
    [DataContract(Name = "FieldAdvancedValue")]
    public partial class FieldAdvancedValue : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldAdvancedValue" /> class.
        /// </summary>
        /// <param name="fieldName">Name of the field (note that spaces will be replaced with underscore).</param>
        /// <param name="fieldStringValue">String value of the field that was extractged from the document.</param>
        public FieldAdvancedValue(string fieldName = default, string fieldStringValue = default)
        {
            this.FieldName = fieldName;
            this.FieldStringValue = fieldStringValue;
        }

        /// <summary>
        /// Name of the field (note that spaces will be replaced with underscore)
        /// </summary>
        /// <value>Name of the field (note that spaces will be replaced with underscore)</value>
        [DataMember(Name = "FieldName", EmitDefaultValue = false)]
        public string FieldName { get; set; }

        /// <summary>
        /// String value of the field that was extractged from the document
        /// </summary>
        /// <value>String value of the field that was extractged from the document</value>
        [DataMember(Name = "FieldStringValue", EmitDefaultValue = false)]
        public string FieldStringValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FieldAdvancedValue {\n");
            sb.Append("  FieldName: ").Append(FieldName).Append("\n");
            sb.Append("  FieldStringValue: ").Append(FieldStringValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
