/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Instances of a policy rule violation
    /// </summary>
    [DataContract(Name = "PolicyRuleViolation")]
    public partial class PolicyRuleViolation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyRuleViolation" /> class.
        /// </summary>
        /// <param name="ruleId">ID of the rule; if no ID was supplied, the ID is the 1-based index of the rule.</param>
        /// <param name="ruleViolationRiskScore">Risk score between 0.0 and 1.0 where values above 0.5 are increasing levels of risk.</param>
        /// <param name="ruleViolationRationale">AI natural language rationale for why this policy was violated.</param>
        public PolicyRuleViolation(string ruleId = default, double ruleViolationRiskScore = default, string ruleViolationRationale = default)
        {
            this.RuleId = ruleId;
            this.RuleViolationRiskScore = ruleViolationRiskScore;
            this.RuleViolationRationale = ruleViolationRationale;
        }

        /// <summary>
        /// ID of the rule; if no ID was supplied, the ID is the 1-based index of the rule
        /// </summary>
        /// <value>ID of the rule; if no ID was supplied, the ID is the 1-based index of the rule</value>
        [DataMember(Name = "RuleId", EmitDefaultValue = false)]
        public string RuleId { get; set; }

        /// <summary>
        /// Risk score between 0.0 and 1.0 where values above 0.5 are increasing levels of risk
        /// </summary>
        /// <value>Risk score between 0.0 and 1.0 where values above 0.5 are increasing levels of risk</value>
        [DataMember(Name = "RuleViolationRiskScore", EmitDefaultValue = false)]
        public double RuleViolationRiskScore { get; set; }

        /// <summary>
        /// AI natural language rationale for why this policy was violated
        /// </summary>
        /// <value>AI natural language rationale for why this policy was violated</value>
        [DataMember(Name = "RuleViolationRationale", EmitDefaultValue = false)]
        public string RuleViolationRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PolicyRuleViolation {\n");
            sb.Append("  RuleId: ").Append(RuleId).Append("\n");
            sb.Append("  RuleViolationRiskScore: ").Append(RuleViolationRiskScore).Append("\n");
            sb.Append("  RuleViolationRationale: ").Append(RuleViolationRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
