/* 
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Result of splitting a document into sub-documents
    /// </summary>
    [DataContract]
    public partial class SplitDocumentResponse :  IEquatable<SplitDocumentResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SplitDocumentResponse" /> class.
        /// </summary>
        /// <param name="successful">True if successful, false otherwise.</param>
        /// <param name="subDocuments">The sub-documents that were identified and extracted from the input document.</param>
        public SplitDocumentResponse(bool? successful = default(bool?), List<SubDocument> subDocuments = default(List<SubDocument>))
        {
            this.Successful = successful;
            this.SubDocuments = subDocuments;
        }
        
        /// <summary>
        /// True if successful, false otherwise
        /// </summary>
        /// <value>True if successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// The sub-documents that were identified and extracted from the input document
        /// </summary>
        /// <value>The sub-documents that were identified and extracted from the input document</value>
        [DataMember(Name="SubDocuments", EmitDefaultValue=false)]
        public List<SubDocument> SubDocuments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SplitDocumentResponse {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  SubDocuments: ").Append(SubDocuments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SplitDocumentResponse);
        }

        /// <summary>
        /// Returns true if SplitDocumentResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SplitDocumentResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SplitDocumentResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.SubDocuments == input.SubDocuments ||
                    this.SubDocuments != null &&
                    this.SubDocuments.SequenceEqual(input.SubDocuments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.SubDocuments != null)
                    hashCode = hashCode * 59 + this.SubDocuments.GetHashCode();
                return hashCode;
            }
        }
    }

}
