/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Result of splitting a document into sub-documents
    /// </summary>
    [DataContract(Name = "SplitDocumentResponse")]
    public partial class SplitDocumentResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SplitDocumentResponse" /> class.
        /// </summary>
        /// <param name="successful">True if successful, false otherwise.</param>
        /// <param name="subDocuments">The sub-documents that were identified and extracted from the input document.</param>
        public SplitDocumentResponse(bool successful = default, List<SubDocument> subDocuments = default)
        {
            this.Successful = successful;
            this.SubDocuments = subDocuments;
        }

        /// <summary>
        /// True if successful, false otherwise
        /// </summary>
        /// <value>True if successful, false otherwise</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// The sub-documents that were identified and extracted from the input document
        /// </summary>
        /// <value>The sub-documents that were identified and extracted from the input document</value>
        [DataMember(Name = "SubDocuments", EmitDefaultValue = false)]
        public List<SubDocument> SubDocuments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SplitDocumentResponse {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  SubDocuments: ").Append(SubDocuments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
