/* 
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// A sub-document extracted from a combined document
    /// </summary>
    [DataContract]
    public partial class SubDocument :  IEquatable<SubDocument>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubDocument" /> class.
        /// </summary>
        /// <param name="startPage">Starting page number (1-indexed) of this sub-document in the original document.</param>
        /// <param name="endPage">Ending page number (1-indexed) of this sub-document in the original document.</param>
        /// <param name="documentDescription">Description of the sub-document including document type and any identifying information such as person name.</param>
        /// <param name="fileBytes">The extracted sub-document as PDF file bytes.</param>
        public SubDocument(int? startPage = default(int?), int? endPage = default(int?), string documentDescription = default(string), byte[] fileBytes = default(byte[]))
        {
            this.StartPage = startPage;
            this.EndPage = endPage;
            this.DocumentDescription = documentDescription;
            this.FileBytes = fileBytes;
        }
        
        /// <summary>
        /// Starting page number (1-indexed) of this sub-document in the original document
        /// </summary>
        /// <value>Starting page number (1-indexed) of this sub-document in the original document</value>
        [DataMember(Name="StartPage", EmitDefaultValue=false)]
        public int? StartPage { get; set; }

        /// <summary>
        /// Ending page number (1-indexed) of this sub-document in the original document
        /// </summary>
        /// <value>Ending page number (1-indexed) of this sub-document in the original document</value>
        [DataMember(Name="EndPage", EmitDefaultValue=false)]
        public int? EndPage { get; set; }

        /// <summary>
        /// Description of the sub-document including document type and any identifying information such as person name
        /// </summary>
        /// <value>Description of the sub-document including document type and any identifying information such as person name</value>
        [DataMember(Name="DocumentDescription", EmitDefaultValue=false)]
        public string DocumentDescription { get; set; }

        /// <summary>
        /// The extracted sub-document as PDF file bytes
        /// </summary>
        /// <value>The extracted sub-document as PDF file bytes</value>
        [DataMember(Name="FileBytes", EmitDefaultValue=false)]
        public byte[] FileBytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubDocument {\n");
            sb.Append("  StartPage: ").Append(StartPage).Append("\n");
            sb.Append("  EndPage: ").Append(EndPage).Append("\n");
            sb.Append("  DocumentDescription: ").Append(DocumentDescription).Append("\n");
            sb.Append("  FileBytes: ").Append(FileBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubDocument);
        }

        /// <summary>
        /// Returns true if SubDocument instances are equal
        /// </summary>
        /// <param name="input">Instance of SubDocument to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubDocument input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StartPage == input.StartPage ||
                    (this.StartPage != null &&
                    this.StartPage.Equals(input.StartPage))
                ) && 
                (
                    this.EndPage == input.EndPage ||
                    (this.EndPage != null &&
                    this.EndPage.Equals(input.EndPage))
                ) && 
                (
                    this.DocumentDescription == input.DocumentDescription ||
                    (this.DocumentDescription != null &&
                    this.DocumentDescription.Equals(input.DocumentDescription))
                ) && 
                (
                    this.FileBytes == input.FileBytes ||
                    (this.FileBytes != null &&
                    this.FileBytes.Equals(input.FileBytes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StartPage != null)
                    hashCode = hashCode * 59 + this.StartPage.GetHashCode();
                if (this.EndPage != null)
                    hashCode = hashCode * 59 + this.EndPage.GetHashCode();
                if (this.DocumentDescription != null)
                    hashCode = hashCode * 59 + this.DocumentDescription.GetHashCode();
                if (this.FileBytes != null)
                    hashCode = hashCode * 59 + this.FileBytes.GetHashCode();
                return hashCode;
            }
        }
    }

}
