/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Model
{
    /// <summary>
    /// Row of a table extracted from a document
    /// </summary>
    [DataContract(Name = "TableResultRow")]
    public partial class TableResultRow : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableResultRow" /> class.
        /// </summary>
        /// <param name="cells">Cells in the row.</param>
        public TableResultRow(List<TableResultCell> cells = default)
        {
            this.Cells = cells;
        }

        /// <summary>
        /// Cells in the row
        /// </summary>
        /// <value>Cells in the row</value>
        [DataMember(Name = "Cells", EmitDefaultValue = false)]
        public List<TableResultCell> Cells { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TableResultRow {\n");
            sb.Append("  Cells: ").Append(Cells).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
