/*
 * Document AI API
 *
 * Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudmersive.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Cloudmersive.APIClient.NETCore.DocumentAI.Client;
using Cloudmersive.APIClient.NETCore.DocumentAI.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NETCore.DocumentAI.Model;

namespace Cloudmersive.APIClient.NETCore.DocumentAI.Test.Api
{
    /// <summary>
    ///  Class for testing AnalyzeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AnalyzeApiTests : IDisposable
    {
        private AnalyzeApi instance;

        public AnalyzeApiTests()
        {
            instance = new AnalyzeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyzeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AnalyzeApi
            //Assert.IsType<AnalyzeApi>(instance);
        }

        /// <summary>
        /// Test AnswerQuestions
        /// </summary>
        [Fact]
        public void AnswerQuestionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DocumentQuestionsRequest? body = null;
            //var response = instance.AnswerQuestions(body);
            //Assert.IsType<DocumentQuestionAnswersResult>(response);
        }

        /// <summary>
        /// Test ApplyRules
        /// </summary>
        [Fact]
        public void ApplyRulesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DocumentPolicyRequest? body = null;
            //var response = instance.ApplyRules(body);
            //Assert.IsType<DocumentPolicyResult>(response);
        }
    }
}
